### ISSUE TITLE
AWK Cheat Sheet missing from repo

### ISSUE THREAD

**Issue by bedar89** [xcad2k/cheat-sheets#106]
I just noticed that your `AWK Cheat Sheet (PDF)` link isn't working. I think you're using Obsidian with this repo, but the assets folder isn't included.

Currently it links to `https://github.com/ChristianLempa/cheat-sheets/blob/main/linux/assets/awk.cheat.sheet.pdf`

**Comment by ChristianLempa** [comment]
deleted it, thanks for letting me know
