### ISSUE TITLE
extfile.cnf error in Windows 10

### ISSUE THREAD

**Issue by aiamk** [xcad2k/cheat-sheets#109]
https://github.com/ChristianLempa/cheat-sheets/blob/d0305c26e5e595176cf04bc8943de06a1bf719ae/misc/ssl-certs.md?plain=1#L34C10-L34C10

`echo "subjectAltName=DNS:your-dns.record,IP:257.10.10.1" >> extfile.cnf`

The double quote will cause an error because it will be included in the configuration file.

**Comment by ChristianLempa** [comment]
Can you tell me which shell, and version you're using @aiamk?

**Comment by aiamk** [comment]
@ChristianLempa sorry it was my mistake, I used command prompt (CMD) instead of windows power shell.

thank you for your efforts,
Best Regards.

**Comment by ChristianLempa** [comment]
No worries :) Glad it's solved!
