### ISSUE TITLE
creating html cheatsheet

### ISSUE THREAD

**Issue by Nidhi1k** [xcad2k/cheat-sheets#55]
This repository contains all you need for starting an html page 
1. h tag
2. p tag 
3. lists
4. forms
5. colors
6. footer
7. br , hr
8. comments
9. tables

**Comment by ChristianLempa** [comment]
Hey @Nidhi1k, thanks for your submit! However, I'm looking for a pure Markdown-based cheat-sheet. It would be useful to get it in one page html.md file. Please let me know if you need help or more info!
Thanks :)
