### ISSUE TITLE
Why are cheat-sheets folders empty

### ISSUE THREAD

**Issue by andjones132** [xcad2k/cheat-sheets#77]
@question After watching your YouTube videos, I came here to find the corresponding documentation, only to find that most of the folders were empty. Your videos indicate that we don't need to write everything down because it will be documented, but when I click on the links, it brings me to empty folders. Is this a short-term thing while you migrate to a new structure, or what is happening? Also, while in transition it would be helpful if you marked each folder name with tags like _WIP, _ToBeUpdated, or some indication that showed which folders contain content vs. just being empty.

**Comment by ChristianLempa** [comment]
Thanks for the heads-up. The plan is to add at least one item into every folder as soon as possible, and in the future only create them when there is something to fill in. I'll take a look.
