### ISSUE TITLE
Obsidian internal links in GitHub

### ISSUE THREAD

**Issue by jrobiii** [xcad2k/cheat-sheets#86]
One thing that I'm not really clear on - is the intent of the cheat-sheets to be viewed in GitHub markdown or in Obsidian markdown.  I absolutely appreciate the Obsidian markdown as it makes using the cheat-sheets in Obsidian painless. 

I think that may be the reason that in the BigSync PR #64 that doctorfree had changed all of the Obsidian internal links into relative GitHub markdown links.

**Comment by ChristianLempa** [comment]
I'm not completely decided on this. For people using Obsidian, it makes the most sense to just use backlinks with double-brackets. But when I want to publish it somewhere else, maybe on GitHub or Cloudflare Pages, the double-brackets won't work.

I think we might just change it to the following pattern:

```text
This is a link to a [second page](folder/page.md) ([[page]]).
```

This would work in any other system like GitHub, GH/CF Pages, etc. But still provide a backlink for Obsidian.

**Comment by ChristianLempa** [comment]
Just a quick update, as Obsidian doesn't rely on double-bracket backlinks, I'll replace them all with Markdown links. That will increase the compatibility in other systems.

**Comment by jrobiii** [comment]
I think that is a great idea. When someone come to this site the initial  expectation would be that this repo would be in GitHub markdown. 

Even if you put a note in the README.md I bet there would still be folks opening issues before they read the note.
